name: windows

on: [push, pull_request]

jobs:

  Build:
    name: ${{matrix.name}} (${{matrix.config}})
    runs-on: ${{matrix.os}}

    env:
      CMAKE_GENERATOR: Ninja

    strategy:
      fail-fast: false
      matrix:
        name: [
          windows-2019-msvc2019,
          windows-2019-msvc2019-win32,
          windows-2019-msvc2019-arm64,
          windows-2019-msvc2019-clang,
          windows-2022-msvc2022,
          windows-2022-msvc2022-win32,
          windows-2022-msvc2022-arm64,
          windows-2022-msvc2022-clang
        ]
        config: [Debug, Release]
        include:
          - name: windows-2019-msvc2019
            os: windows-2019
            compiler: cl
            architecture: x64
            version2: win64_msvc2019_64
            qtversion: 6.4.2

          - name: windows-2019-msvc2019-win32
            os: windows-2019
            compiler: cl
            architecture: x86
            version2: win32_msvc2019
            qtversion: 5.15.2

          - name: windows-2019-msvc2019-arm64
            os: windows-2019
            compiler: cl
            architecture: x64_arm64
            version2: win64_msvc2019_arm64
            qtversion: 6.4.2

          - name: windows-2019-msvc2019-clang
            os: windows-2019
            compiler: clang-cl
            architecture: x64
            version2: win64_msvc2019_64
            qtversion: 6.4.2

          - name: windows-2022-msvc2022
            os: windows-2022
            compiler: cl
            architecture: x64
            version2: win64_msvc2019_64
            qtversion: 6.4.2

          - name: windows-2022-msvc2022-win32
            os: windows-2022
            compiler: cl
            architecture: x86
            version2: win32_msvc2019
            qtversion: 5.15.2

          - name: windows-2022-msvc2022-arm64
            os: windows-2022
            compiler: cl
            architecture: x64_arm64
            version2: win64_msvc2019_arm64
            qtversion: 6.4.2

          - name: windows-2022-msvc2022-clang
            os: windows-2022
            compiler: clang-cl
            architecture: x64
            version2: win64_msvc2019_64
            qtversion: 6.4.2

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.architecture}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{matrix.qtversion}}'
          host: 'windows'
          target: 'desktop'
          arch: '${{matrix.version2}}'
          cache: 'true'

      - name: Install Qt (Host)
        if: matrix.architecture == 'x64_arm64'
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{matrix.qtversion}}'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: 'true'

       - name: Cache Dependencies
        id: cache-choco
        uses: actions/cache@v4
        env:
          cache-name: cache-choco-packages
        with:
          path: C:/Users/runneradmin/AppData/Local/Temp/chocolatey
          key: ${{env.cache-name}}

      - name: Dependencies
        run: |
             choco install ninja -y
             choco install doxygen.install graphviz -y
             if ( "${{matrix.architecture}}" -eq "x64_arm64" ) {
               echo "Qt6_DIR=${{runner.workspace}}/Qt/${{matrix.qtversion}}/msvc2019_arm64" >> $env:GITHUB_ENV
               echo "QT_PLUGIN_PATH=${{runner.workspace}}/Qt/${{matrix.qtversion}}/msvc2019_arm64/plugins" >> $env:GITHUB_ENV
               echo "QML2_IMPORT_PATH=${{runner.workspace}}/Qt/${{matrix.qtversion}}/msvc2019_arm64/qml" >> $env:GITHUB_ENV
               echo "QT_HOST_PATH=${{runner.workspace}}/Qt/${{matrix.qtversion}}/msvc2019_64/" >> $env:GITHUB_ENV
             }

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake $env:GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=${{matrix.config}}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.config}}

#      - name: Test
#        if: ${{ matrix.architecture != 'x64_arm64' && matrix.name != 'windows-2022-msvc2022' }}
#        working-directory: ${{runner.workspace}}/build
#        run: ctest --output-on-failure -C ${{matrix.config}}

      - name: Documentation
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target documentation
